[package]
name = "cctrusted_base"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
anyhow = "1.0"
base64 = "0.13.0"
log = "0.4.14"
serde_json = "1.0"
sha2 = "0.10"
nix = "0.26.2"
lazy_static = "1.4.0"
